version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - node
      - db
    networks:
      - node-network
  
  node:
    build:
      context: ./node
    container_name: node
    restart: always
    volumes:
      - ./node:/app
      - /app/node_modules
    tty: true
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - node-network

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0 | copy ./mysql/setup.sql /docker-entrypoint-initdb.d/
    restart: always
    tty: true
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge