version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports: 
      - '8080:80'
    depends_on:
      - node
    networks:
      - node-network
  
  node:
    container_name: node
    restart: always
    build:
      context: ./node
    volumes:
      - ./node:/app
    depends_on:
      - db
    ports:
      - '3000:3000'
    networks:
      - node-network

  db:
    build: 
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
networks:
  node-network:
    driver: bridge